rlg:
  project-info:
    version: 1.0
  module-info:
    name: auth
    version: 1.0
  swagger:
    version: ${rlg.project-info.version}
    group-name: ${rlg.module-info.name}
    title: 身份认证
    description: 红叶园多功能生活服务平台身份认证中心后台API文档
    term-of-service-url: http://www.apache.org/licenses/LICENSE-2.0
    contact-name: 一只枫兔
    contact-url: http://mabbit.icu
    contact: schuke@foxmail.com

spring:
  profiles:
    active: dev

springdoc:
  packages-to-scan: icu.mabbit.rlg.auth.controller