rlg:
  project-info:
    version: 1.0
  swagger:
    version: ${rlg.project-info.version}
    group-name: ${rlg.module-info.name}
  # security配置
  security:
    enable-login-auth: true
    # url白名单
    uri-white-list:
      - /doc.html
      - /webjars/**
      - /favicon.ico
      - /swagger-resources
      - /v2/api-docs

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev