spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    include:
      - module
    active: test

rlg:
  project-info:
    version: 1.0
  swagger:
    version: ${rlg.project-info.version}
    group-name: ${rlg.module-info.name}
  # security配置
  security:
    enable-login-auth: true